const findings=[
{id:'DVWA-01',title:'Command Injection',severity:'Critical',score:'9.8',domain:'Injection',summary:'Unsanitized input reaches an operating-system command.',impact:'Remote command execution with the web-server account may expose files, credentials, and connected services.',root:'The application concatenates untrusted input into a shell command.',fix:['Replace shell construction with fixed APIs.','Apply strict allowlists and type validation.','Run the service with least privilege and monitor process execution.']},
{id:'DVWA-02',title:'SQL Injection',severity:'Critical',score:'9.4',domain:'Injection',summary:'User input changes the structure of a database query.',impact:'An attacker may extract data, bypass authentication, or modify application records.',root:'Dynamic SQL is built by concatenating request values.',fix:['Use parameterized queries everywhere.','Apply typed validation at trust boundaries.','Use a least-privilege database account.']},
{id:'DVWA-03',title:'Unrestricted File Upload',severity:'High',score:'8.8',domain:'File Handling',summary:'Upload validation trusts filenames and client-controlled metadata.',impact:'Executable or dangerous content may be stored and later invoked.',root:'Extension and MIME checks are incomplete and storage is web-accessible.',fix:['Verify extension, MIME, and file signatures.','Generate server-side filenames.','Store uploads outside the executable web root.']},
{id:'DVWA-04',title:'File Inclusion',severity:'High',score:'8.4',domain:'File Handling',summary:'A request parameter controls a server-side include path.',impact:'Sensitive local files or executable resources may be loaded.',root:'Untrusted paths are passed directly to file-loading logic.',fix:['Map identifiers to fixed templates.','Canonicalize and validate paths.','Disable remote inclusion and restrict filesystem permissions.']},
{id:'DVWA-05',title:'Stored Cross-Site Scripting',severity:'High',score:'8.0',domain:'Client-Side',summary:'Persistent user content is rendered without contextual encoding.',impact:'A payload can execute for later visitors, hijack sessions, or alter content.',root:'Stored data is treated as trusted HTML when rendered.',fix:['Encode output by context.','Sanitize approved rich content.','Deploy a restrictive Content Security Policy.']},
{id:'DVWA-06',title:'Reflected Cross-Site Scripting',severity:'High',score:'7.6',domain:'Client-Side',summary:'Request input is reflected directly into the response.',impact:'Crafted links may execute attacker-controlled script in a victim browser.',root:'The response inserts raw request values into HTML.',fix:['Use contextual output encoding.','Use safe DOM APIs.','Apply CSP as defense in depth.']},
{id:'DVWA-07',title:'Cross-Site Request Forgery',severity:'High',score:'7.3',domain:'Session Security',summary:'A state-changing action lacks validated anti-CSRF protection.',impact:'A logged-in user can be tricked into submitting an unwanted action.',root:'The server accepts ambient credentials without proving request intent.',fix:['Use per-session anti-CSRF tokens.','Set SameSite cookies.','Require re-authentication for sensitive actions.']},
{id:'DVWA-08',title:'Brute-Force Authentication',severity:'Medium',score:'6.9',domain:'Authentication',summary:'Login attempts are not effectively throttled or challenged.',impact:'Weak credentials may be discovered through repeated guesses.',root:'Authentication lacks rate limits, progressive delay, and MFA.',fix:['Add rate limiting and backoff.','Offer MFA.','Monitor credential-stuffing patterns.']},
{id:'DVWA-09',title:'Insecure CAPTCHA Validation',severity:'Medium',score:'6.5',domain:'Authentication',summary:'The server trusts client-controlled CAPTCHA workflow state.',impact:'Automation may bypass the intended human-verification step.',root:'Challenge completion is not verified independently on the server.',fix:['Validate challenge state server-side.','Bind challenges to sessions and actions.','Expire and invalidate tokens after use.']},
{id:'DVWA-10',title:'Weak Session Cookie Controls',severity:'Medium',score:'6.8',domain:'Session Security',summary:'Session cookies lack appropriate security attributes.',impact:'Client-side script or insecure transport may expose session identifiers.',root:'Cookie policy omits HttpOnly, Secure, or appropriate SameSite settings.',fix:['Set HttpOnly, Secure, and SameSite.','Rotate IDs after authentication.','Enforce idle and absolute timeouts.']}
];
const grid=document.querySelector('#grid'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent'),search=document.querySelector('#search'),count=document.querySelector('#count');let active='all';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function evidence(f,i){return i%2===0?`<div class="evidence"><div class="evidence-bar">authorized-terminal · ${esc(f.id)}</div><code>$ labscan --case ${esc(f.id)}<br><span class="ok">[+] target:</span> dvwa.local<br><span class="warn">[!] weakness:</span> ${esc(f.title)}<br><span class="bad">[!] severity:</span> ${esc(f.severity)} / ${esc(f.score)}<br><span class="ok">[✓] evidence captured</span></code></div>`:`<div class="evidence report"><span class="badge">${esc(f.severity.toUpperCase())} · ${esc(f.score)}</span><h4>${esc(f.title)}</h4><hr><p><b>Finding record</b></p><p>${esc(f.summary)}</p><hr><small>REMEDIATION PRIORITY: ${esc(f.severity)}</small></div>`}
function card(f,i){return `<article class="finding" data-severity="${esc(f.severity)}">${evidence(f,i)}<div class="finding-body"><div class="meta"><span>${esc(f.id)} · ${esc(f.domain)}</span><span class="severity ${esc(f.severity)}">${esc(f.severity)}</span></div><h3>${esc(f.title)}</h3><p>${esc(f.summary)}</p><button class="open" data-id="${esc(f.id)}">Open full case ↗</button></div></article>`}
function render(){const q=search.value.trim().toLowerCase();const rows=findings.filter(f=>(active==='all'||f.severity===active)&&(`${f.id} ${f.title} ${f.domain}`.toLowerCase().includes(q)));grid.innerHTML=rows.map((f,i)=>card(f,i)).join('')||'<p class="lead">No findings match this search.</p>';count.textContent=`${rows.length} case${rows.length===1?'':'s'}`;document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openCase(b.dataset.id))}
function openCase(id){const f=findings.find(x=>x.id===id);modalContent.innerHTML=`<p class="eyebrow">${esc(f.id)} · ${esc(f.domain)} · SCORE ${esc(f.score)}</p><h2>${esc(f.title)}</h2><p><span class="severity ${esc(f.severity)}">${esc(f.severity)}</span></p>${evidence(f,0)}<h3>Observed weakness</h3><p>${esc(f.summary)}</p><h3>Impact</h3><p>${esc(f.impact)}</p><h3>Root cause</h3><p>${esc(f.root)}</p><h3>Recommended controls</h3><ul>${f.fix.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Controlled-lab procedure</h3><ol><li>Confirm the isolated DVWA target and selected security level.</li><li>Submit a focused test input and record the request context.</li><li>Compare the observable result with expected secure behavior.</li><li>Preserve evidence and map the root cause to defensive action.</li></ol>`;modal.showModal()}
document.querySelector('#close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;render()});search.oninput=render;document.querySelector('#menu').onclick=()=>document.querySelector('#nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>document.querySelector('#nav').classList.remove('open'));window.addEventListener('scroll',()=>{const h=document.documentElement;document.querySelector('#progress').style.width=`${(h.scrollTop/(h.scrollHeight-h.clientHeight))*100}%`});render();